# Basic Python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {} kilometers .'.format(planet,diameter));

The diameter of Earth kilometers .


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
np.arange(20,35)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b))
print(c)


[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
data =[['Prabha',19],['Anusha',20],['sivaranjini',23]]
df=pd.DataFrame(data, columns=['Name','Age'])
print(df)

          Name  Age
0       Prabha   19
1       Anusha   20
2  sivaranjini   23


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import date
def numKOfDates(date1,date2): 
  return(date2-date1)
  date1= date(2023,1,1)
  date2= date(2023,2,10)
  print(numOfDates(date1,date2),"dates")

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd 
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
x=pd.DataFrame(lists)
print(x)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
